tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = true
generate_mono_repository_global_tag = true
branch_whitelist = ["main"]
post_bump_hooks = [
    "git push",
    "git push origin v{{version}}",
]

pre_bump_hooks = [
    "cargo set-version --workspace {{version}}",
    "cargo build --release",
]

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
